### ISSUE TITLE
 httpRequest.setEntity(builder.build());

### ISSUE THREAD

**Issue by BraveAction** [com314159/VolleyMultiPartRequest#1]
caught a NoSuchFieldError for com.zjkj.yuerbao
    java.lang.NoSuchFieldError: org.apache.http.message.BasicHeaderValueFormatter.INSTANCE

**Comment by com314159** [comment]
can you give me a demo or more log.  Maybe you can update the httpclient and httpcore and httpmime jar and try if it will caught this error.   In my app, I haven't got this error.

**Comment by BraveAction** [comment]
07-22 10:25:23.756  15806-16347/com.zjkj.yuerbao E/ACRA﹕ com.zjkj.yuerbao fatal error : org.apache.http.message.BasicHeaderValueFormatter.INSTANCE
    java.lang.NoSuchFieldError: org.apache.http.message.BasicHeaderValueFormatter.INSTANCE
            at org.apache.http.entity.ContentType.toString(ContentType.java:153)
            at org.apache.http.entity.mime.MultipartFormEntity.<init>(MultipartFormEntity.java:53)
            at org.apache.http.entity.mime.MultipartEntityBuilder.buildEntity(MultipartEntityBuilder.java:236)
            at org.apache.http.entity.mime.MultipartEntityBuilder.build(MultipartEntityBuilder.java:240)
            at com.zjkj.yuerbao.common.util.volley.MultiPartStack.setMultiPartBody(MultiPartStack.java:178)
            at com.zjkj.yuerbao.common.util.volley.MultiPartStack.createMultiPartRequest(MultiPartStack.java:120)
            at com.zjkj.yuerbao.common.util.volley.MultiPartStack.performMultiPartRequest(MultiPartStack.java:66)
            at com.zjkj.yuerbao.common.util.volley.MultiPartStack.performRequest(MultiPartStack.java:54)
            at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
            at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)

ps-I'm sorry, it's too late.
I am a Chinese, my English is not good.

**Comment by BraveAction** [comment]
i haven got this jar
httpclient-4.5.jar
httpcore-4.4.1.jar
httpmime-4.5.jar

**Comment by com314159** [comment]
你这个是必现的吗?  是用AndroidStudio的?  我查了一下, 不管你是用AndroidStudio还是eclipse, 出现这个错误基本上都是配置lib出的问题. 你可以先用我这个demo把接口接入, 上传一下, 这个我是测试过的. 然后看下lib jar哪里出错了.  这个是参考链接: http://stackoverflow.com/questions/28711754/android-eclipse-error-on-file-upload-to-server   另外你可以升级一下这些jar, 下载地址http://mvnrepository.com/(从这个地址搜索一下)

**Comment by BraveAction** [comment]
http://stackoverflow.com/questions/28711754/android-eclipse-error-on-file-upload-to-server-试过了也不行
jar-是从http://search.maven.org上找的，我分析应该也是jar的问题

mcxiaoke commented 9 days ago
volley does not support multipart by default, you can check other libraries.

现在服务器端图片上传要求用base64传输，规避了这个问题，有时间再研究一下吧！谢谢！

**Comment by com314159** [comment]
en, 我给的jar应该是没问题的, 感觉是引入jar的问题, 有空你再看一下. 好的.

**Comment by BelongsH** [comment]
最后怎么用中文了。。

**Comment by j20120307** [comment]
apache 在api 23已经被deprecated 了，求教应该如何上传？

**Comment by com314159** [comment]
@j20120307  你找一下有没有替代的方法? 我们公司用的还是这个api. 这个库我暂时没空去维护它, 最近在研究新产品, 还得做iOS开发.

**Comment by xiaoCong2014** [comment]
看头两条评论，我还以为你们是外国人呢，结果居然全是中国人！英文突然变中文
